Bosses:
  #This requires a server restart/reload to change!
  hoursBetween: 1
  commandToExecute: "mm m spawn Azel 1 world,-147,25,-59"
  messagesToBroadcast:
    - '&6&lThe boss &e&l&nAzel&r &6&lhas spawned.'
    - '&7&oDefeat him in the WarZone to claim the reward.'
    - ''
    - '&6&lBOSS REWARDS &8»'
    - '&e* Shards &6(100%%)'
    - '&e* Random Blocks & Items &6(100%%)'
  soundToPlay:
    sound: ENTITY_WITHER_SPAWN
    pitch: 1
    volume: 0.5
Pouches:
  normalchest:
    name: '&a&lSTARTER POUCH &7&o(Right Click)'
    messageToSend: '&b&lZenith &8| &7You are opening a Starter Pouch.'
    commandToExecute: 'cc open Starter %player%'
    soundToPlay:
      sound: ENTITY_ITEM_PICKUP
      pitch: 1
      volume: 10
  enderchest:
    name: '&6&l&nLEGENDARY SPIN&r &7&o(Right Click)'
    messageToSend: '&b&lZenith &8| &7You are spinning the wheel.'
    commandToExecute: 'cc open Legendary %player%'
    soundToPlay:
      sound: ENTITY_ITEM_PICKUP
      pitch: 1
      volume: 10
Tips:
  craftingtable:
    messagesToSend:
      - ''
      - '&b&lZenith &8| &7You can enable or disable &3FastCrafting &7with ""&3&n/fc toggle&7""&7.'
      - ''
    soundToPlay:
      sound: ENTITY_ITEM_PICKUP
      pitch: 1
      volume: 10
  spawner:
    messagesToSend:
      - ''
      - '&b&lZenith &8| &7Mob Spawners can only be broken with &3Silk Touch&7. You can upgrade to &3&lGold&r &7to toggle SilkTouch on your pickaxe! View all of the donator perks with "&3&n/buy&7" or at &3&nstore.store.zen-mc.net&7.'
      - ''
    soundToPlay:
      sound: ENTITY_ITEM_PICKUP
      pitch: 1
      volume: 10
Rewards:
  messagesToSend:
    - ''
    - '&a$10,000 (100%%)'
    - '&a2 McMMO Credits (100%%)'
    - '&aVote Key (100%%)'
    - '&6$50,000 (35%%)'
    - '&625 McMMO Credits (35%%)'
    - '&6Rare Key (35%%)'
    - '&cBlaze Spawner (5%%)'
    - '&cIron Golem Spawner (5%%)'
    - '&4&lVillager Spawner (1%%)'
    - ''